module Graphics
  def getting_logo
    logo = []
    logo[0] = '  _  _                '.center(40)
    logo[1] = ' | || |__ _ _ _  __ _ '.center(40)
    logo[2] = ' | __ / _` | \' \/ _` |'.center(40)
    logo[3] = ' |_||_\__,_|_||_\__, |'.center(40)
    logo[4] = ' |  \/  |__ _ _ |___/ '.center(40)
    logo[5] = ' | |\/| / _` | \' \    '.center(40)
    logo[6] = ' |_|  |_\__,_|_||_|   '.center(40)
    logo[7] = 'by: @LuisHernandezCoding'.center(40)
    logo
  end

  def getting_menu_block(title, option1, option2, option3, option4)
    block = []
    block << ' '.center(40)
    block << '     ╔════════════════════════════╗     '
    block << '     ║                            ║     '
    block << "     ║#{title.center(28)}║     "
    block << '     ║                            ║     '
    block << '     ╚══╦══════════════════════╦══╝     '
    block << "        ║#{"1. #{option1}".center(22)}║        "
    block << '        ║ """""""""""""""""""" ║        '
    block << "        ║#{"2. #{option2}".center(22)}║        "
    block << '        ║ """""""""""""""""""" ║        '
    block << "        ║#{"3. #{option3}".center(22)}║        "
    block << '        ║ """""""""""""""""""" ║        '
    block << "        ║#{"4. #{option4}".center(22)}║        "
    block << '        ║ """""""""""""""""""" ║        '
    block << '        ╚══════════════════════╝        '
    block << ' '.center(40)
  end

  def getting_animation(step = 10)
    animation_args = []
    case step
    when 0
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /                     '
      animation_args << '  ║ ║ / /                      '
      animation_args << '  ║ ║/ /                       '
      animation_args << '  ║ ║ /                        '
      animation_args << '  ║ ║/                         '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 1
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /                     '
      animation_args << '  ║ ║ / /                      '
      animation_args << '  ║ ║/ /                       '
      animation_args << '  ║ ║ /                        '
      animation_args << '  ║ ║/                         '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║               ,~~~.      '
      animation_args << '  ║ ║             _/ _ _ \\_    '
      animation_args << '  ║ ║             \| °.° |/    '
      animation_args << '  ║ ║               \ - /      '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 2
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /                     '
      animation_args << '  ║ ║ / /                      '
      animation_args << '  ║ ║/ /                       '
      animation_args << '  ║ ║ /                        '
      animation_args << '  ║ ║/                         '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║                          '
      animation_args << '  ║ ║               ,~~~.      '
      animation_args << '  ║ ║             _/ _ _ \_    '
      animation_args << '  ║ ║             \| °.° |/    '
      animation_args << '  ║ ║               \ - /      '
      animation_args << '  ║ ║             ___/ \___    '
      animation_args << '  ║ ║            //Y . . Y\\\\   '
      animation_args << '  ║ ║           // ║     ║ \\\\  '
      animation_args << '  ║ ║          //  ║  .  ║  \\\\ '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 3
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /                     '
      animation_args << '  ║ ║ / /                      '
      animation_args << '  ║ ║/ /                       '
      animation_args << '  ║ ║ /                        '
      animation_args << '  ║ ║/              ,~~~.      '
      animation_args << '  ║ ║             _/ _ _ \\_    '
      animation_args << '  ║ ║             \| °.° |/    '
      animation_args << '  ║ ║               \ - /      '
      animation_args << '  ║ ║             ___/ \___    '
      animation_args << '  ║ ║            //Y . . Y\\\\   '
      animation_args << '  ║ ║           // ║     ║ \\\\  '
      animation_args << '  ║ ║          //  ║  .  ║  \\\\ '
      animation_args << '  ║ ║         (~)  ║═════║  (~)'
      animation_args << '  ║ ║         "¨¨  ║║═══║║  ¨¨"'
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 4
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /                     '
      animation_args << '  ║ ║ / /           ,~~~.      '
      animation_args << '  ║ ║/ /          _/ _ _ \_    '
      animation_args << '  ║ ║ /           \| °.° |/    '
      animation_args << '  ║ ║/              \ - /      '
      animation_args << '  ║ ║             ___/ \___    '
      animation_args << '  ║ ║            //Y . . Y\\\\   '
      animation_args << '  ║ ║           // ║     ║ \\\\  '
      animation_args << '  ║ ║          //  ║  .  ║  \\\\ '
      animation_args << '  ║ ║         (~)  ║═════║  (~)'
      animation_args << '  ║ ║         "¨¨  ║║═══║║  ¨¨"'
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║             / ║   ║ \\    '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 5
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /     ()              '
      animation_args << '  ║ ║ / /      ()   ,~~~.      '
      animation_args << '  ║ ║/ /       ()  / _ _ \     '
      animation_args << '  ║ ║ /           /_ °   0     '
      animation_args << '  ║ ║/            \  ´´´´/     '
      animation_args << '  ║ ║              \__´´´\     '
      animation_args << '  ║ ║            //Y . . Y\\\\   '
      animation_args << '  ║ ║           // ║     ║ \\\\  '
      animation_args << '  ║ ║          //  ║  .  ║  \\\\ '
      animation_args << '  ║ ║         (~)  ║═════║  (~)'
      animation_args << '  ║ ║         "¨¨  ║║═══║║  ¨¨"'
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║             / ║   ║ \\    '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 6
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /     ()              '
      animation_args << '  ║ ║ / /      ()   ,~~~.      '
      animation_args << '  ║ ║/ /       ()  / _ _ \     '
      animation_args << '  ║ ║ /        () /_ °   0     '
      animation_args << '  ║ ║/         () \  ´´´´/     '
      animation_args << '  ║ ║          ()  \__´´´\     '
      animation_args << '  ║ ║            //Y . . Y\\\\   '
      animation_args << '  ║ ║           // ║     ║ \\\\  '
      animation_args << '  ║ ║          //  ║  .  ║  \\\\ '
      animation_args << '  ║ ║         (~)  ║═════║  (~)'
      animation_args << '  ║ ║         "¨¨  ║║═══║║  ¨¨"'
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║             / ║   ║ \\    '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 7
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /     ()              '
      animation_args << '  ║ ║ / /      ()   ,~~~.      '
      animation_args << '  ║ ║/ /       ()  / _ _ \     '
      animation_args << '  ║ ║ /        () /_ °   0     '
      animation_args << '  ║ ║/         () \  ´´´´/     '
      animation_args << '  ║ ║         ()() \__´´´\     '
      animation_args << '  ║ ║        ()  //Y . . Y\\\\   '
      animation_args << '  ║ ║         ()// ║     ║ \\\\  '
      animation_args << '  ║ ║          //  ║  .  ║  \\\\ '
      animation_args << '  ║ ║         (~)  ║═════║  (~)'
      animation_args << '  ║ ║         "¨¨  ║║═══║║  ¨¨"'
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║              ║║   ║║     '
      animation_args << '  ║ ║             / ║   ║ \\    '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 8
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /     ()              '
      animation_args << '  ║ ║ / /      () ,~~~.        '
      animation_args << '  ║ ║/ /       ()/  _  \\       '
      animation_args << '  ║ ║ /        ()0  °  _\\      '
      animation_args << '  ║ ║/         ()\````  /      '
      animation_args << '  ║ ║          ()/```__/       '
      animation_args << '  ║ ║          /Y . . Y\\\\      '
      animation_args << '  ║ ║         // ║   ║ \\\\      '
      animation_args << '  ║ ║        //  ║ . ║  \\\\     '
      animation_args << '  ║ ║       (~)  ║═══║  (~)    '
      animation_args << '  ║ ║       "¨¨  ║║═║║  ¨¨"    '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║           / ║ ║ \\        '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 9
      animation_args << '  ╔════════════()══════╗       '
      animation_args << '  ║ ╔══════════()══════╝       '
      animation_args << '  ║ ║  / /     ()              '
      animation_args << '  ║ ║ / /      () ,~~~.        '
      animation_args << '  ║ ║/ /       ()/  _  \\       '
      animation_args << '  ║ ║ /        ()0  °  _\\      '
      animation_args << '  ║ ║/         ()\````  /      '
      animation_args << '  ║ ║          ()OOOOOO/       '
      animation_args << '  ║ ║          /Y . . Y\\\\      '
      animation_args << '  ║ ║         // ║   ║ \\\\      '
      animation_args << '  ║ ║        //  ║ . ║  \\\\     '
      animation_args << '  ║ ║       (~)  ║═══║  (~)    '
      animation_args << '  ║ ║       "¨¨  ║║═║║  ¨¨"    '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║           / ║ ║ \\        '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 10
      animation_args << '  ╔════════════║)══════╗       '
      animation_args << '  ║ ╔══════════(║══════╝       '
      animation_args << '  ║ ║  / /     ║)              '
      animation_args << '  ║ ║ / /      (║ ,~~~.        '
      animation_args << '  ║ ║/ /       ║)/  _  \\       '
      animation_args << '  ║ ║ /        (║0  °  _\\      '
      animation_args << '  ║ ║/         ║)\````  /      '
      animation_args << '  ║ ║           (0000000       '
      animation_args << '  ║ ║          /Y . . Y\\\\      '
      animation_args << '  ║ ║         // ║   ║ \\\\      '
      animation_args << '  ║ ║        //  ║ . ║  \\\\     '
      animation_args << '  ║ ║       (~)  ║═══║  (~)    '
      animation_args << '  ║ ║       "¨¨  ║║═║║  ¨¨"    '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║           / ║ ║ \\        '
      animation_args << '""""""""""""║═════════════║"""║/8'
      animation_args << '"""║"║""""""║═════════════║"║"║/ '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
      animation_args << '  ║ ║                     ║ ║  '
    when 11
      animation_args << '  ╔════════════║║══════╗       '
      animation_args << '  ║ ╔══════════║║══════╝       '
      animation_args << '  ║ ║  / /     ║║              '
      animation_args << '  ║ ║ / /      ║║              '
      animation_args << '  ║ ║/ /       ║║ ,~~~.        '
      animation_args << '  ║ ║ /        ║║/  _  \\       '
      animation_args << '  ║ ║/         ║║0  x  _\\      '
      animation_args << '  ║ ║          ║║\````/_/      '
      animation_args << '  ║ ║           ║║║║║║║║       '
      animation_args << '  ║ ║          /Y . . Y\\\\      '
      animation_args << '  ║ ║         // ║   ║ \\\\      '
      animation_args << '  ║ ║        //  ║ . ║  \\\\     '
      animation_args << '  ║ ║       (~)  ║═══║  (~)    '
      animation_args << '  ║ ║       "¨¨  ║║═║║  ¨¨"    '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '  ║ ║            ║║ ║║         '
      animation_args << '"""""""""""║_   / ║ ║ \\ .║"""║  '
      animation_args << '""║"║""""""\ \  `-\' `-\' \'║"║"║\ '
      animation_args << '  ║ ║       \ \           ║ ║ \8'
      animation_args << '  ║ ║        \ \          ║ ║  '
      animation_args << '  ║ ║         \ \         ║ ║  '
      animation_args << '  ║_║          \'\'         ║_║  '
      animation_args << '  ║ ║                     ║ ║  '
    end
    animation_args.each_with_index do |arg, index|
      animation_args[index] = arg.center(34)
    end
  end
end